---
title: Get started
---

El objetivo de
[infoelectoral](https://hmeleiro.github.io/infoelectoral/) es facilitar
la descarga y el procesamiento necesario para analizar datos oficiales
de resultados electorales del Ministerio de Interior. En la web del
ministerio es posible descargarse ficheros a nivel de mesa y municipio.
Sin embargo, el formato de los ficheros (texto plano sin delimitar) y la
estructura del diseño de registro (la información útil para el análisis
de los procesos electorales está dispersa en al menos tres ficheros
distintos) hace algo costoso la importación de los datos a cualquier
entorno de análisis.

Para descargar los datos a nivel de municipio se dispone de la función
`municipios()` a la cual hay que proporcionar el tipo de elección
deseada (“congreso”, “municipales” o “europeas”, el Ministerio del
Interior no dispone de los datos de los procesos electorales
autonómicos), el año (YYYY) y el mes (MM) del proceso electoral.

    library(infoelectoral)
    df <- municipios(tipo_eleccion = "congreso", anno = "1979", mes = "03")
    str(df)

    ## 'data.frame':    119422 obs. of  34 variables:
    ##  $ tipo_eleccion            : chr  "02" "02" "02" "02" ...
    ##  $ anno                     : chr  "1979" "1979" "1979" "1979" ...
    ##  $ mes                      : chr  "03" "03" "03" "03" ...
    ##  $ vuelta                   : chr  "1" "1" "1" "1" ...
    ##  $ codigo_ccaa              : chr  "14" "14" "14" "14" ...
    ##  $ codigo_provincia         : chr  "01" "01" "01" "01" ...
    ##  $ codigo_municipio         : chr  "001" "001" "001" "001" ...
    ##  $ municipio                : chr  "Alegría-Dulantzi" "Alegría-Dulantzi" "Alegría-Dulantzi" "Alegría-Dulantzi" ...
    ##  $ codigo_distrito          : chr  "99" "99" "99" "99" ...
    ##  $ codigo_distrito_electoral: chr  "0" "0" "0" "0" ...
    ##  $ codigo_partido_judicial  : chr  "059" "059" "059" "059" ...
    ##  $ codigo_diputacion        : chr  "059" "059" "059" "059" ...
    ##  $ codigo_comarca           : chr  "000" "000" "000" "000" ...
    ##  $ poblacion_derecho        : num  972 972 972 972 972 972 972 972 972 972 ...
    ##  $ numero_mesas             : num  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ censo_ine                : num  681 681 681 681 681 681 681 681 681 681 ...
    ##  $ censo_escrutinio         : num  681 681 681 681 681 681 681 681 681 681 ...
    ##  $ censo_cere               : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ votantes_cere            : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ participacion_1          : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ participacion_2          : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ votos_blancos            : num  2 2 2 2 2 2 2 2 2 2 ...
    ##  $ votos_nulos              : num  23 23 23 23 23 23 23 23 23 23 ...
    ##  $ votos_candidaturas       : num  482 482 482 482 482 482 482 482 482 482 ...
    ##  $ numero_concejales        : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ codigo_partido_nacional  : chr  "000036" "000019" "000067" "000047" ...
    ##  $ codigo_partido_autonomia : chr  "000036" "000019" "000067" "000047" ...
    ##  $ codigo_partido_provincia : chr  "000036" "000019" "000067" "000047" ...
    ##  $ codigo_partido           : chr  "000036" "000019" "000067" "000047" ...
    ##  $ denominacion             : chr  "PARTIDO CARLISTA" "HERRI BATASUNA" "PARTIDO UNION NACIONAL" "EUZKO ALDERDI JELTZALEA-PARTIDO NACIONALISTA VASCO" ...
    ##  $ siglas                   : chr  "PCARL" "HB" "UN" "PNV" ...
    ##  $ votos                    : num  3 27 18 132 18 4 121 12 5 3 ...
    ##  $ datos_oficiales          : chr  "N" "N" "N" "N" ...
    ##  $ concejales_obtenidos     : num  0 0 0 0 0 0 0 0 0 0 ...

Para descargar elecciones a nivel de mesa:

    df <- mesas("congreso", "2019", "04")
    str(df)

    ## 'data.frame':    712175 obs. of  28 variables:
    ##  $ tipo_eleccion           : chr  "02" "02" "02" "02" ...
    ##  $ anno                    : chr  "2019" "2019" "2019" "2019" ...
    ##  $ mes                     : chr  "04" "04" "04" "04" ...
    ##  $ vuelta                  : chr  "1" "1" "1" "1" ...
    ##  $ codigo_ccaa             : chr  "14" "14" "14" "14" ...
    ##  $ codigo_provincia        : chr  "01" "01" "01" "01" ...
    ##  $ codigo_municipio        : chr  "001" "001" "001" "001" ...
    ##  $ municipio               : chr  "Alegría-Dulantzi" "Alegría-Dulantzi" "Alegría-Dulantzi" "Alegría-Dulantzi" ...
    ##  $ codigo_distrito         : chr  "01" "01" "01" "01" ...
    ##  $ codigo_seccion          : chr  "001" "002" "002" "001" ...
    ##  $ codigo_mesa             : chr  "B" "A" "B" "B" ...
    ##  $ censo_ine               : num  492 512 518 492 512 492 483 512 518 492 ...
    ##  $ censo_cera              : num  492 512 518 492 512 492 483 512 518 492 ...
    ##  $ censo_cere              : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ votantes_cere           : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ participacion_1         : num  221 219 218 221 219 221 141 219 218 221 ...
    ##  $ participacion_2         : num  309 334 328 309 334 309 278 334 328 309 ...
    ##  $ votos_blancos           : num  2 1 0 2 1 2 1 1 0 2 ...
    ##  $ votos_nulos             : num  5 6 2 5 6 5 6 6 2 5 ...
    ##  $ votos_candidaturas      : num  355 353 377 355 353 355 330 353 377 355 ...
    ##  $ codigo_partido_nacional : chr  "000066" "000033" "000083" "000083" ...
    ##  $ codigo_partido_autonomia: chr  "000067" "000033" "000083" "000083" ...
    ##  $ codigo_partido_provincia: chr  "000067" "000033" "000083" "000083" ...
    ##  $ codigo_partido          : chr  "000067" "000033" "000083" "000083" ...
    ##  $ denominacion            : chr  "PARTIDO COMUNISTA DE LOS TRABAJADORES DE EUSKADI/E" "EUSKAL HERRIA BILDU" "PARTIDO POPULAR" "PARTIDO POPULAR" ...
    ##  $ siglas                  : chr  "PCTE/ELAK" "EH Bildu" "PP" "PP" ...
    ##  $ votos                   : num  0 59 35 18 10 108 52 85 1 69 ...
    ##  $ datos_oficiales         : chr  "S" "S" "S" "S" ...

La librería [infoelectoral](https://hmeleiro.github.io/infoelectoral/)
también dispone de funciones para descargar datos de candidatos al
senado y al Congreso de los Diputados. La función `senado()` permite la
descarga de los resultados electorales de cada candidato al Senado.

    df <- senado(anno = "2019", mes = "11", nivel = "municipio")
    str(df)

    ## 'data.frame':    195539 obs. of  39 variables:
    ##  $ tipo_eleccion            : chr  "03" "03" "03" "03" ...
    ##  $ anno                     : chr  "2019" "2019" "2019" "2019" ...
    ##  $ mes                      : chr  "11" "11" "11" "11" ...
    ##  $ vuelta                   : chr  "1" "1" "1" "1" ...
    ##  $ codigo_ccaa              : chr  "14" "14" "14" "14" ...
    ##  $ codigo_provincia         : chr  "01" "01" "01" "01" ...
    ##  $ codigo_distrito_electoral: chr  "9" "9" "9" "9" ...
    ##  $ codigo_municipio         : chr  "034" "056" "011" "009" ...
    ##  $ municipio                : chr  "Leza" "Harana / Valle de Arana" "Baños de Ebro / Mañueta" "Asparrena" ...
    ##  $ codigo_distrito          : chr  "99" "99" "99" "99" ...
    ##  $ numero_mesas             : num  1 1 1 2 2 1 1 2 3 1 ...
    ##  $ poblacion_derecho        : num  196 229 286 1643 1445 ...
    ##  $ censo_ine                : num  152 202 213 1258 1091 ...
    ##  $ censo_escrutinio         : num  152 202 213 1258 1091 ...
    ##  $ censo_cere               : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ votantes_cere            : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ participacion_1          : num  66 50 93 484 441 67 197 711 811 335 ...
    ##  $ participacion_2          : num  90 86 132 674 590 ...
    ##  $ votos_blancos            : num  3 2 6 10 6 2 3 21 28 7 ...
    ##  $ votos_nulos              : num  3 2 2 16 15 1 14 16 44 16 ...
    ##  $ votos_candidaturas       : num  100 105 153 811 706 ...
    ##  $ codigo_partido_nacional  : chr  "000018" "000018" "000018" "000018" ...
    ##  $ codigo_partido_autonomia : chr  "000018" "000018" "000018" "000018" ...
    ##  $ codigo_partido_provincia : chr  "000018" "000018" "000018" "000018" ...
    ##  $ codigo_partido           : chr  "000018" "000018" "000018" "000018" ...
    ##  $ denominacion             : chr  "CIUDADANOS-PARTIDO DE LA CIUDADANÍA" "CIUDADANOS-PARTIDO DE LA CIUDADANÍA" "CIUDADANOS-PARTIDO DE LA CIUDADANÍA" "CIUDADANOS-PARTIDO DE LA CIUDADANÍA" ...
    ##  $ siglas                   : chr  "Cs" "Cs" "Cs" "Cs" ...
    ##  $ codigo_senador           : chr  "019016" "019016" "019016" "019016" ...
    ##  $ orden_candidato          : num  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ tipo_candidato           : chr  "T" "T" "T" "T" ...
    ##  $ nombre                   : chr  "Cristian" "Cristian" "Cristian" "Cristian" ...
    ##  $ apellido_1               : chr  "Martínez" "Martínez" "Martínez" "Martínez" ...
    ##  $ apellido_2               : chr  "Conca" "Conca" "Conca" "Conca" ...
    ##  $ sexo                     : chr  "M" "M" "M" "M" ...
    ##  $ nacimiento               : Date, format: "2021-12-12" "2021-12-12" ...
    ##  $ dni                      : chr  "0000000000" "0000000000" "0000000000" "0000000000" ...
    ##  $ votos                    : num  0 0 3 3 12 1 3 18 48 12 ...
    ##  $ electo                   : chr  "N" "N" "N" "N" ...
    ##  $ datos_oficiales          : chr  "S" "S" "S" "S" ...

Por último, la función `candidatos()` permite la descarga de la
información de los candidatos al Congreso de los Diputados, a los
ayuntamientos y al Parlamento Europeo.

    df <- candidatos("europeas", "2019", "05")
    str(df)

    ## 'data.frame':    9859 obs. of  22 variables:
    ##  $ tipo_eleccion           : chr  "07" "07" "07" "07" ...
    ##  $ anno                    : chr  "2019" "2019" "2019" "2019" ...
    ##  $ mes                     : chr  "05" "05" "05" "05" ...
    ##  $ vuelta                  : chr  "1" "1" "1" "1" ...
    ##  $ codigo_provincia        : chr  "01" "01" "01" "01" ...
    ##  $ codigo_municipio        : chr  "001" "002" "003" "004" ...
    ##  $ codigo_distrito         : chr  "99" "99" "99" "99" ...
    ##  $ orden_candidato         : num  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ tipo_candidato          : chr  NA NA NA NA ...
    ##  $ nombre                  : chr  NA NA NA NA ...
    ##  $ apellido_1              : chr  NA NA NA NA ...
    ##  $ apellido_2              : chr  NA NA NA NA ...
    ##  $ sexo                    : chr  NA NA NA NA ...
    ##  $ nacimiento              : logi  NA NA NA NA NA NA ...
    ##  $ dni                     : logi  NA NA NA NA NA NA ...
    ##  $ electo                  : chr  NA NA NA NA ...
    ##  $ codigo_partido_nacional : chr  NA NA NA NA ...
    ##  $ codigo_partido_autonomia: chr  NA NA NA NA ...
    ##  $ codigo_partido_provincia: chr  NA NA NA NA ...
    ##  $ codigo_partido          : chr  NA NA NA NA ...
    ##  $ denominacion            : chr  NA NA NA NA ...
    ##  $ siglas                  : chr  NA NA NA NA ...
